### ISSUE TITLE
all the programs arent consistent

### ISSUE THREAD

**Issue by int-72h** [Riesi/Riesi#6]
some do different things than others
at least make it consistent :frog: :stuffed_flatbread:

**Comment by kassindornelles** [comment]
riesi

**Comment by Riesi** [comment]
riesi

**Comment by git-bruh** [comment]
:frog_whip:

**Comment by int-72h** [comment]
ok made them a bit more consistent

**Comment by kassindornelles** [comment]
2023 and its still incosistent dead project we need riesi-staging back

**Comment by int-72h** [comment]
shut up kassin
